name: my_cafe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.0
  cupertino_icons: ^1.0.2
  dotted_dashed_line: ^0.0.3
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1
  flutter_svg: ^2.0.7
  get: ^4.6.6
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.2
  intl_phone_field: ^3.2.0
  lottie: ^2.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
